# Generated by Django 4.2.6 on 2023-10-12 07:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_image_height', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(1)])),
                ('can_see_original', models.BooleanField(default=False)),
                ('can_generate_links', models.BooleanField(default=False)),
                ('link_livespan', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tier'),
        ),
    ]
