# Generated by Django 4.2.6 on 2023-10-15 07:24

from django.db import migrations


def populate_account_tiers(apps, schema_editor):
    Tier = apps.get_model("core", "Tier")
    if Tier.objects.count() == 0:
            Tier.objects.create(
                name='Basic',
                max_thumbnail_height=200,
                can_see_original=False,
                can_generate_links=False
            )
            Tier.objects.create(
                name='Premium',
                max_thumbnail_height=400,
                can_see_original=True,
                can_generate_links=False
            )
            Tier.objects.create(
                name='Enterprise',
                max_thumbnail_height=400,
                can_see_original=True,
                can_generate_links=True
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_max_image_height_tier_max_thumbnail_height_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_account_tiers)
    ]
